PIPELINE_HOME_VAR = "PIPELINE_HOME"
TRAIN_DATASET_FOLDER_NAME = "train"
MODELS_FOLDER_NAME = "models"
DATASET_FILE_NAME = "dataset.csv"

APPLICATION_FOLDER_NAME = "applications"

APPLICATION_CONFIG_FILE_NAME = "config.json"

LINEAR_REGRESSION_MODEL_NAME = "lr_model.pkl"
DNN_MODEL_NAME = "dnn_model.hdf5"
DECISION_TREE_REGRESSOR_MODEL_NAME = "dtr_model.pkl"
#TODO: FILL THESE UP